apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      name: app
      labels:
        app: app
    spec:
      containers:
        - image: airlinedemoreg.azurecr.io/app:latest
          imagePullPolicy: IfNotPresent
          name: app
          ports:
            - containerPort: 8080
      imagePullSecrets:
        - name: airlinedemoreg.azurecr.io-pull-secret
---
apiVersion: v1
kind: Service
metadata:
  name: app
spec:
  selector:
    app: app
  type: LoadBalancer
  ports:
    - port: 8080